### ISSUE TITLE
Installation Prerequisites on GNU/Linux

### ISSUE THREAD

**Issue by caliuf** [McSinyx/palace#111] opened 2020-07-29 14:02 UTC
Hi everyone,
I'm trying to install palace through pip, but I'm having some issues.

Initially the installation failed with:
`subprocess.CalledProcessError: Command '['cmake', '.']' returned non-zero exit status 1.` 

Since there was no significant information about the error, I modified setup.py in order to display the standard error of the subprocess (I'll submit a PR for that)

The first problem was:  

      CMake Error at CMakeLists.txt:2 (project):
      No CMAKE_CXX_COMPILER could be found.
    
      Tell CMake where to find the compiler by setting either the environment
      variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
      to the compiler, or to the compiler name if it is in the PATH.

I rerun with the command `export CXX=g++-8 ; pip install` but then I got stuck with this one:

      CMake Error at CMakeLists.txt:3 (find_package):
      Could not find a package configuration file provided by "Alure2" with any
      of the following names:
    
        Alure2Config.cmake
        alure2-config.cmake
    
      Add the installation prefix of "Alure2" to CMAKE_PREFIX_PATH or set
      "Alure2_DIR" to a directory containing one of the above files.  If "Alure2"
      provides a separate development package or SDK, be sure it has been
      installed.

On Ubuntu I only see these packages that can match: libalure1, libalure-dev. Neither one provide the *.cmake files required.

Is there a package providing "alure2" on apt or snap or should I have to build and install it? (The repo is [kcat/alure](https://github.com/kcat/alure)?)

Last note: If the doc happens to be incomplete I would gladly send a PR for it too :-)

**Comment by McSinyx** [comment] 2020-07-29 14:25
Thank you for reporting this!  While I suspect it's our fault in not providing enough instructions on how to successfully build the project, we might need some additional information from your side as well.  [The return values of `platform.platform()`, `platform.python_version()` and `platform.python_compiler()`](https://mcsinyx.github.io/palace/html/contributing.html#reporting-a-bug) might be all we need.  These probably need to land in an issue template but all of us are a bit busy with other things in life for quite a while, so please take our apologies :smile:

With the above provided, we can confirm my suspicion that you're on an non-amd64 architecture, which we have yet to build wheels for.  That should explains why setup.py is invoked.  BTW I'd welcome PR logging debugging information from CMake invocation in setup.py, after setting things up I only had to deal with compiler errors :wink:

I'm a bit surprised that you met

> No CMAKE_CXX_COMPILER could be found.

@9a24f0 also uses Ubuntu for the development of this project and I don't recall him complaining about this.  Maybe you two are using different versions of the distro, still it's weird that Ubuntu doesn't config CMake/gcc out of box.  I encountered this problem on neither Debian (testing) nor NixOS.

To answer your last question, yes it is supposed to be alure 2, which hasn't been packaged for any distro other than NixOS AFAIK.  The compilation instructions for alure can be found in [the project's README](https://github.com/kcat/alure).

**Comment by caliuf** [comment] 2020-07-29 14:39
Thanks for the quick reply! No problem, I'll be your Intel tester :smile: 

Here's my system info:

    >>> platform.platform()
    'Linux-4.15.0-112-generic-x86_64-with-LinuxMint-19.1-tessa'
    >>> platform.python_version()
    '3.7.5'
    >>> platform.python_compiler()
    'GCC 8.3.0'

Alas, I have zero expertise with C++, so probably I will end up to some dumb questions on that regard.

I will install alure from sources in a couple of hours and I'll report here.

I'm keeping note of the steps I had to take in the installation process on Linux Mint (Ubuntu derivative), I'll add a paragraph in the doc when I'm finished, if it's ok for you :-)

**Comment by McSinyx** [comment] 2020-07-29 14:45
Strange, the wheels should be installed just fine (amd64 and x86_64 refer to the same architecture BTW).  I wonder what happens when you run `pip install --prefer-binary palace`.  You might need to use pip3, or preferably `python3 -m pip`, in place of pip if your pip is installed from the distro's repository.

**Comment by caliuf** [comment] 2020-07-29 17:15
Whoa, in fact pip version installed in my virtual env was 9.0.1, my distro's original one.
I upgraded it and now I'm currently running python 3.7, with pip 20.2.

Using `pip install --prefer-binary palace` worked fine.

For me it's ok now and the issue could be closed, tell me if you'd like me to do some other trials in order to get basic `pip install` run on my system

**Comment by McSinyx** [comment] 2020-07-30 03:48
I'm glad that it's working now!  BTW since the issue was with outdated pip, I think you shouldn't even need the `--prefer-binary` flag.  The wheel is shipped with alure, openal and a few others library, so you can even uninstall them from your system if you don't need them.  I'll go ahead and close it for now, feel free to reopen if you still have any question.

**Closed as completed by McSinyx** 2020-07-30 03:48 UTC
Labels: documentation, question, distribution

**Comment by caliuf** [comment] 2020-07-30 09:32
@McSinyx Alas, after upgrading pip the error remained unchanged. Only --prefer-binary was able to do the trick.

**Comment by McSinyx** [comment] 2020-07-30 09:38
Which version of palace do you get with `pip install --prefer-binary palace`?  IIRC pip always prefer binarys/wheels by default unless there exists an sdist of a higher version and the palace's latest release 0.2.0 does provide a wheel for CPython 3.7.

**Comment by caliuf** [comment] 2020-07-30 09:51
I've did my trials (with and without --prefer-binary) after upgrading pip:

    (venv) $ python --version
    Python 3.7.5
    (venv) $ pip --version
    pip 20.2 from .../palace/venv/lib/python3.7/site-packages/pip (python 3.7)

I'm not intimate with the inner workings of pip, so I may be missing something. It's a good chance to learn, tough.

**Comment by McSinyx** [comment] 2020-07-30 09:56
I meant the version of palace, which can be obtained by `pip show palace` after installation.

**Comment by caliuf** [comment] 2020-07-30 10:01
Sorry, I mistakenly took it for granted: 0.2.0 (latest one if I'm correct)

**Comment by McSinyx** [comment] 2020-07-30 10:06
This is not expected, could you please file an issue over pip with the commands to reproduce that pip chooses to build the source distribution (don't emphasize on that the build fail :smile: that'd be palace's problem) over using the wheel.  I'll catch up with you there.  I should file the issue myself but I can't reproduce that on my system so…

**Comment by caliuf** [comment] 2020-07-30 18:03
@McSinyx While I was opening the pip issue I've tried to reproduce the problem but (luckily) without success, pip 20.2 correctly uses the binaries, without forcing it.

I've probably confused terminals during latest test or something like that, don't know. 

Sorry, I think we can consider this really closed :smile:
